// columnsConfig.js

const columnasValidasFase1 = [
    "ID",
    "Nombre",
    "Primer apellido",
    "Segundo apellido",
    "Email",
    "Estado",
    "% Avance",
    "Fecha de creación",
    "Fecha envío",
    "Nombre Postulación",
    "¿La iniciativa corresponde a alguna de las siguientes modalidades de Internacionalización Virtual?",
    "Nombre de la Iniciativa VcM",
    "Sede",
    "Unidad o Dependencia Responsable",
    "Escuela/Carrera Facultad de Ciencias Sociales y Artes",
    "Escuela/Carrera Facultad de Ciencias, Ingeniería y Tecnología",
    "Facultad de Medicina y Ciencias de la Salud",
    "Centro de Investigación",
    "Otras Unidades No Académicas",
    "Otras Unidades No Académicas",
    "Programas de Postgrado",
    "¿La iniciativa es organizada en conjunto con otras unidades académicas o administrativas?",
    "Unidades Co-organizadoras",
    "Otras Unidades No Académicas Co-organizadoras",
    "Fecha de Inicio de la Iniciativa",
    "Fecha de Término de la Iniciativa",
    "Mecanismo VcM sugerido",
    "Antigüedad de la Iniciativa VcM",
    "¿La iniciativa fue ejecutada con presupuesto VcM en 2024?",
    "En caso afirmativo, indique el Código VcM asignado",
    "Descripción y Acciones de la Iniciativa",
    "¿La iniciativa está orientada a formación académica? (Vinculación Académica - VA)",
    "¿La iniciativa incluye interacción directa con actores externos?",
    "¿La iniciativa es parte de un curso o asignatura?",
    "Mencione el nombre de la asignatura o curso",
    "¿La iniciativa se basa en diagnósticos o problemáticas comunitarias?",
    "¿La actividad involucra a más de una disciplina o área de conocimiento?",
    "¿La iniciativa implica la difusión y/o intercambio de conocimiento? (Articulación e Intercambio de Conocimiento - AIC)",
    "¿El contenido se adapta al público objetivo externo?",
    "¿Incluye talleres, capacitaciones o asesorías técnicas?",
    "¿Se promueve el diálogo bidireccional con actores externos?",
    "¿La iniciativa es una actividad cultural o artística? (Vinculación Artístico-Cultural - VAC)",
    "¿Fomenta la participación de la comunidad externa?",
    "¿Incluye co-creación con actores externos?",
    "¿Promueve la diversidad cultural?",
    "¿La iniciativa incluye investigación básica, aplicada o emprendimiento? (Investigación, Proyectos de Emprendimiento y Estudios - IPEE)",
    "¿Participan actores externos en la formulación o implementación?",
    "¿Se busca resolver problemáticas concretas del entorno?",
    "¿Se generan productos o soluciones prácticas?",
    "¿La iniciativa implica alianzas internacionales? (Internacionalización - INT)",
    "¿Incluye movilidad académica o estudiantil?",
    "¿Se desarrollan proyectos de investigación colaborativa internacional?",
    "¿Se promueve el intercambio cultural o académico?",
    "¿La iniciativa está orientada a graduados/titulados y/o empleadores? (Graduados/Titulados, Empleabilidad y Redes - GTER)",
    "¿Incluye retroalimentación curricular con empleadores?",
    "¿Se fomenta la empleabilidad de los graduados?",
    "¿Se promueven redes profesionales?",
    "¿La iniciativa responde a problemáticas identificadas con actores externos?",
    "¿Cómo se identificaron estas problemáticas?",
    "Modalidad de Implementación de la Iniciativa",
    "Alcance Territorial de la Iniciativa",
    "Tipo de Público Externo Participante",
    "Otro Tipo de Público Externo Participante",
    "Ámbitos Estratégicos que Aborda la Iniciativa",
    "Objetivos de Desarrollo Sostenible (ODS) que Apoya la Iniciativa",
    "Competencias Sello Institucionales Potenciadas por la Iniciativa",
    "Tipo de Acceso a la Iniciativa",
    "Requerimiento de Financiamiento VcM",
    "Monto de Financiamiento VcM Requerido",
    "Uso del Presupuesto Solicitado",
    "Si seleccionó \"Otro uso\", especifique el destino del presupuesto",
    "Fuente de Financiamiento Externo",
    "Acceso a la Iniciativa",
    "Si corresponde, indique el nombre de la organización o actor externo con el que ya cuente con un compromiso o acuerdo de trabajo",
    "¿Qué objetivos espera alcanzar para la universidad con esta iniciativa?",
    "¿Qué objetivos espera alcanzar para los actores externos con esta iniciativa?",
    "¿Se planea dar continuidad a la iniciativa en el futuro?",
    "¿La actividad generará alianzas, convenios o redes de colaboración que podrían mantenerse activas?",
    "Herramientas de Evaluación de la Iniciativa",
    "Otros Instrumentos Necesarios para Evaluar la Iniciativa",
    "Alineación Estratégica con la Unidad de Origen",
    "Potencial de Multidisciplina o Interdisciplina",
    "Antigüedad de la Actividad",
    "Diagnóstico de Necesidad o Interés",
    "Relación con Actores Externos",
    "Alcance de la Contribución",
    "Generación de Conocimiento y Retroalimentación",
    "Factibilidad Técnico-Presupuestaria",
    "Validación Unidad de Origen (0.0%)",
    "Validación Vinculación con el Medio (100.0%)",
    "Nota final"
];
