// columnsConfig.js
const columnasValidasFase1 = [
    "ID",
    "Nombre",
    "Primer apellido",
    "Segundo apellido",
    "Email",
    "Estado",
    "% Avance",
    "Fecha de creación",
    "Fecha envío",
    "Nombre Postulación",
    "¿La iniciativa corresponde a alguna de las siguientes modalidades de Internacionalización Virtual?",
    "Nombre de la Iniciativa VcM",
    "Sede",
    "Unidad o Dependencia Responsable",
    "Escuela/Carrera Facultad de Ciencias Sociales y Artes",
    "Escuela/Carrera Facultad de Ciencias, Ingeniería y Tecnología",
    "Facultad de Medicina y Ciencias de la Salud",
    "Centro de Investigación",
    "Otras Unidades No Académicas",
    "Otras Unidades No Académicas",
    "Programas de Postgrado",
    "¿La iniciativa es organizada en conjunto con otras unidades académicas o administrativas?",
    "Unidades Co-organizadoras",
    "Otras Unidades No Académicas Co-organizadoras",
    "Fecha de Inicio de la Iniciativa",
    "Fecha de Término de la Iniciativa",
    "Mecanismo VcM sugerido",
    "Antigüedad de la Iniciativa VcM",
    "¿La iniciativa fue ejecutada con presupuesto VcM en 2024?",
    "En caso afirmativo, indique el Código VcM asignado",
    "Descripción y Acciones de la Iniciativa",
    "¿La iniciativa está orientada a formación académica? (Vinculación Académica - VA)",
    "¿La iniciativa incluye interacción directa con actores externos?",
    "¿La iniciativa es parte de un curso o asignatura?",
    "Mencione el nombre de la asignatura o curso",
    "¿La iniciativa se basa en diagnósticos o problemáticas comunitarias?",
    "¿La actividad involucra a más de una disciplina o área de conocimiento?",
    "¿La iniciativa implica la difusión y/o intercambio de conocimiento? (Articulación e Intercambio de Conocimiento - AIC)",
    "¿El contenido se adapta al público objetivo externo?",
    "¿Incluye talleres, capacitaciones o asesorías técnicas?",
    "¿Se promueve el diálogo bidireccional con actores externos?",
    "¿La iniciativa es una actividad cultural o artística? (Vinculación Artístico-Cultural - VAC)",
    "¿Fomenta la participación de la comunidad externa?",
    "¿Incluye co-creación con actores externos?",
    "¿Promueve la diversidad cultural?",
    "¿La iniciativa incluye investigación básica, aplicada o emprendimiento? (Investigación, Proyectos de Emprendimiento y Estudios - IPEE)",
    "¿Participan actores externos en la formulación o implementación?",
    "¿Se busca resolver problemáticas concretas del entorno?",
    "¿Se generan productos o soluciones prácticas?",
    "¿La iniciativa implica alianzas internacionales? (Internacionalización - INT)",
    "¿Incluye movilidad académica o estudiantil?",
    "¿Se desarrollan proyectos de investigación colaborativa internacional?",
    "¿Se promueve el intercambio cultural o académico?",
    "¿La iniciativa está orientada a graduados/titulados y/o empleadores? (Graduados/Titulados, Empleabilidad y Redes - GTER)",
    "¿Incluye retroalimentación curricular con empleadores?",
    "¿Se fomenta la empleabilidad de los graduados?",
    "¿Se promueven redes profesionales?",
    "¿La iniciativa responde a problemáticas identificadas con actores externos?",
    "¿Cómo se identificaron estas problemáticas?",
    "Modalidad de Implementación de la Iniciativa",
    "Alcance Territorial de la Iniciativa",
    "Tipo de Público Externo Participante",
    "Otro Tipo de Público Externo Participante",
    "Ámbitos Estratégicos que Aborda la Iniciativa",
    "Objetivos de Desarrollo Sostenible (ODS) que Apoya la Iniciativa",
    "Competencias Sello Institucionales Potenciadas por la Iniciativa",
    "Tipo de Acceso a la Iniciativa",
    "Requerimiento de Financiamiento VcM",
    "Monto de Financiamiento VcM Requerido",
    "Uso del Presupuesto Solicitado",
    "Si seleccionó \"Otro uso\", especifique el destino del presupuesto",
    "Fuente de Financiamiento Externo",
    "Acceso a la Iniciativa",
    "Si corresponde, indique el nombre de la organización o actor externo con el que ya cuente con un compromiso o acuerdo de trabajo",
    "¿Qué objetivos espera alcanzar para la universidad con esta iniciativa?",
    "¿Qué objetivos espera alcanzar para los actores externos con esta iniciativa?",
    "¿Se planea dar continuidad a la iniciativa en el futuro?",
    "¿La actividad generará alianzas, convenios o redes de colaboración que podrían mantenerse activas?",
    "Herramientas de Evaluación de la Iniciativa",
    "Otros Instrumentos Necesarios para Evaluar la Iniciativa",
    "Alineación Estratégica con la Unidad de Origen",
    "Potencial de Multidisciplina o Interdisciplina",
    "Antigüedad de la Actividad",
    "Diagnóstico de Necesidad o Interés",
    "Relación con Actores Externos",
    "Alcance de la Contribución",
    "Generación de Conocimiento y Retroalimentación",
    "Factibilidad Técnico-Presupuestaria",
    "Validación Unidad de Origen (0.0%)",
    "Validación Vinculación con el Medio (100.0%)",
    "Nota final"
];

const columnasValidasFase2 = [
    "ID",
    "Nombre",
    "Primer apellido",
    "Segundo apellido",
    "Email",
    "Estado",
    "% Avance",
    "Fecha de creación",
    "Fecha envío",
    "Nombre Postulación",
    "Describa la ejecución de su iniciativa VcM",
    "¿De qué manera contribuyó su iniciativa al Modelo de Vinculación con el Medio de la Universidad?",
    "Por favor, describa brevemente en qué consistió esta contribución:",
    "¿Cuál fue el aporte más relevante de su iniciativa VcM a la comunidad externa involucrada?",
    "Describa brevemente en qué consistió este aporte",
    "¿Su iniciativa VcM contempló la participación planificada de estudiantes (de pregrado y/o postgrado) en el desarrollo de actividades?",
    "¿A qué competencias y/o conocimientos del perfil de egreso contribuyó la participación de los/as estudiantes en esta iniciativa?",
    "Describa las acciones desarrolladas por los/as estudiantes en el marco de la iniciativa.",
    "Realice una evaluación cualitativa de la participación de los/as estudiantes en la iniciativa.",
    "¿Cómo evaluaría el conocimiento teórico demostrado por los/as estudiantes durante su participación en la iniciativa?",
    "¿Cómo evaluaría el desempeño actitudinal de los/as estudiantes durante su participación en la iniciativa?",
    "¿Cómo evaluaría el desempeño procedimental de los/as estudiantes durante su participación en la iniciativa?",
    "¿Cuál fue la principal fortaleza observada en los/as estudiantes durante su participación en la iniciativa?",
    "Por favor, comente las fortalezas observadas en los/as estudiantes durante su participación en la iniciativa.",
    "¿Cuál fue la principal debilidad observada en los/as estudiantes durante su participación en la iniciativa?",
    "Por favor, puntualice otras debilidades observadas en los/as estudiantes durante su participación en la iniciativa.",
    "¿La iniciativa fue planificada como parte de una o más asignaturas del plan de estudios?",
    "A partir de la experiencia vivida en la iniciativa, ¿qué ajustes o mejoras sugiere incorporar a la(s) asignatura(s) involucrada(s)?",
    "¿La iniciativa incluyó la participación activa y planificada de actores externos (organizaciones, instituciones o grupos del entorno)?",
    "¿Qué aprendizajes surgieron a partir de la interacción con la(s) organización(es) o institución(es) externa(s) participantes?",
    "¿De qué manera estos aprendizajes contribuyeron a su quehacer académico o disciplinar?",
    "Especifique de qué otra forma estos aprendizajes contribuyeron a su quehacer académico o disciplinar",
    "Aprendizajes obtenidos del contacto con comunidades y sus contextos",
    "¿De qué manera estos aprendizajes fortalecieron su quehacer profesional o disciplinar?",
    "Puntualice otra forma en que estos aprendizajes fortalecieron su quehacer profesional o disciplinar",
    "¿Considera que su iniciativa VcM contribuyó a la empleabilidad e inserción laboral futura de los estudiantes?",
    "Contribución a la inserción laboral y al conocimiento mutuo entre estudiantes y empleadores",
    "Beneficios específicos obtenidos para la inserción laboral",
    "Puntualice el o los otros beneficios que se obtuvieron para la inserción laboral",
    "Hallazgos relevantes identificados durante la ejecución de la iniciativa",
    "¿Qué áreas temáticas fueron impactadas por los hallazgos identificados?",
    "Por favor, puntualice la(s) otra(s) área(s) temática(s) influenciada(s) por los hallazgos derivados de su iniciativa",
    "Nuevas líneas de trabajo identificadas a partir de los hallazgos de su iniciativa",
    "¿Cómo pueden contribuir estas nuevas líneas de trabajo al desarrollo futuro?",
    "Puntualice la(s) otra(s) contribución(es) al desarrollo futuro de estas nuevas líneas de trabajo",
    "Retroalimentación obtenida a través de instrumentos de evaluación (encuestas, grupos focales, entrevistas, etc.)",
    "¿Cómo puede esta retroalimentación contribuir a futuras actividades o mejoras?",
    "Puntualice otras formas en que esta retroalimentación puede ser útil para futuras actividades o mejoras",
    "Número de estudiantes de pregrado participantes",
    "Número de estudiantes de postgrado participantes",
    "Número de titulados o graduados involucrados",
    "Número de académicos/as involucrados",
    "Número de beneficiarios o asistentes externos: personas naturales",
    "¿Cuántas personas aproximadamente participaron o asistieron a su iniciativa? (Sólo en caso de no contar con un número exacto de asistentes externos)",
    "Número de organizaciones externas participantes",
    "Por favor, mencione las organizaciones o actores externos que participaron en la iniciativa.",
    "Dificultades en la ejecución y sugerencias de mejora",
    "¿Qué tipo de dificultades se presentaron durante la ejecución de la iniciativa?",
    "Puntualice la o las otras dificultades que se hayan presentado durante la ejecución de la iniciativa.",
    "¿Qué tipo de ajustes considera necesarios para futuras versiones de la iniciativa?",
    "Por favor, comente los ajustes o modificaciones que considere necesarios para futuras implementaciones de la iniciativa.",
    "Alineación Estratégica con la Unidad de Origen",
    "Potencial de Multidisciplina o Interdisciplina",
    "Antigüedad de la Actividad",
    "Diagnóstico de Necesidad o Interés",
    "Relación con Actores Externos",
    "Alcance de la Contribución",
    "Generación de Conocimiento y Retroalimentación",
    "Factibilidad Técnico-Presupuestaria",
    "Validación Unidad de Origen (0.0%)",
    "Validación Vinculación con el Medio (100.0%)",
    "Nota final"
];